# -*- coding: utf-8 -*-
"""KishorLab-1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vx-tKeaeM_PjUNQZ5FolPcVjtunqLkzP
"""

import pandas as pd
print("Kishor Lab")

df = pd.read_csv('employee_data.csv')
print("Initial Data:\n", df.head())

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

df['Department'] = df['Department'].str.strip().replace({
    'Human Resources': 'HR',
    'H.R.': 'HR',
    'hr': 'HR'
})

print("\nCleaned Data:\n", df.head())

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv('student_scores.csv')
print("Initial Data:\n", df.head())
scaler = MinMaxScaler()
df[['Math', 'Science', 'English']] = scaler.fit_transform(df[['Math', 'Science', 'English']])
print("\nNormalized Scores:\n", df.head())

import pandas as pd
print("Discretization")
df = pd.read_csv('customer_ages.csv')
print("Initial Data:\n", df.head())
bins = [18, 30, 50, 100]
labels = ['Young', 'Middle-aged', 'Senior']
df['Group'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

print("\nData after Binning:\n", df.head())

dist = df['Group'].value_counts()
print("\nAge Group Distribution:\n", dist)

import pandas as pd
df = pd.read_csv('sales_data.csv')
print("Initial Data:\n", df.head())
bins = [0, 5000, 20000, float('inf')]
labels = ['Low', 'Medium', 'High']
df['Category'] = pd.cut(df['Sales'], bins=bins, labels=labels)
print("\nData after Discretization:\n", df.head())
dist = df['Category'].value_counts()
print("\nSales Category Distribution:\n", dist)

import pandas as pd
from sklearn.feature_selection import SelectKBest, chi2

df = pd.read_csv('medical_data.csv')
print("Initial Data:\n", df.head())

X = df.drop(columns=['Disease'])
y = df['Disease']

sel = SelectKBest(score_func=chi2, k=3)
sel.fit(X, y)

top = X.columns[sel.get_support()]
print("\nTop 3 Features for Predicting Disease:\n", top.tolist())